name: demirbasim
description: Demirbaş takip uygulaması.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino ikonları
  cupertino_icons: ^1.0.2

  # Animasyon
  animated_splash_screen: 1.3.0
  flutter_spinkit: 5.2.0

  # Resimlerin önbelleğe alınması
  cached_network_image: 3.2.1
  flutter_cache_manager: 3.3.0

  # Google Places API
  flutter_google_places:
    git:
      url: https://github.com/fluttercommunity/flutter_google_places
      ref: v0.3.2

  # Font Awesome ikonları
  font_awesome_flutter: 10.1.0

  # Google fontları
  google_fonts: 4.0.3

  # Google hesap doğrulama
  google_sign_in: 6.0.2
  google_sign_in_android: 6.1.8
  google_sign_in_ios: 5.6.1
  google_sign_in_platform_interface: 2.4.0
  google_sign_in_web: 0.11.0+2

  # State yönetimi
  provider: 6.0.4

  # Dosya işlemleri
  path_provider: 2.0.9
  shared_preferences: 2.1.1
  sqflite: 2.2.6

  # Tarih işlemleri
  timeago: 3.2.2
  #path 
  path: ^1.8.0
  # URL açma
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_platform_interface: 2.1.2

  # Firebase
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2

  # Resim seçme ve kırpma
  image_picker: ^0.8.6
  image_cropper: ^1.4.1
  connectivity_plus: ^2.1.0


 

dev_dependencies:
  # Uygulama simgesi
  flutter_launcher_icons: ^0.13.1
  # Kod üreticisi
  build_runner: ^2.0.6

  # Kod testleri
  flutter_test:
    sdk: flutter

  # Kodlama standartları
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/