// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlSWMwaJzu99oRzoRtl2LrqRvD5IJOKUY',
    appId: '1:896529393110:web:0dd6f3bbaee93783023077',
    messagingSenderId: '896529393110',
    projectId: 'demirbasim',
    authDomain: 'demirbasim.firebaseapp.com',
    storageBucket: 'demirbasim.appspot.com',
    measurementId: 'G-BCBDE9SMHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaTXBloeH3A-48djidK_Xy6eWry_rXr7M',
    appId: '1:896529393110:android:7df0ffbe283065e1023077',
    messagingSenderId: '896529393110',
    projectId: 'demirbasim',
    storageBucket: 'demirbasim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz2knqP4McZwjbtQeebiw_eDfwbGu15ts',
    appId: '1:896529393110:ios:069b49d94cf37ce9023077',
    messagingSenderId: '896529393110',
    projectId: 'demirbasim',
    storageBucket: 'demirbasim.appspot.com',
    iosClientId: '896529393110-qnfi6unrgkqo0070nerl8u1fjn8q0113.apps.googleusercontent.com',
    iosBundleId: 'com.example.demirbasim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz2knqP4McZwjbtQeebiw_eDfwbGu15ts',
    appId: '1:896529393110:ios:069b49d94cf37ce9023077',
    messagingSenderId: '896529393110',
    projectId: 'demirbasim',
    storageBucket: 'demirbasim.appspot.com',
    iosClientId: '896529393110-qnfi6unrgkqo0070nerl8u1fjn8q0113.apps.googleusercontent.com',
    iosBundleId: 'com.example.demirbasim',
  );
}
